// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkfZUq_sJNd6OiicrqHQVqvmSTijs2BZk',
    appId: '1:411331360468:web:df653180b1c040f55a2d41',
    messagingSenderId: '411331360468',
    projectId: 'gggg-2ee00',
    authDomain: 'gggg-2ee00.firebaseapp.com',
    storageBucket: 'gggg-2ee00.appspot.com',
    measurementId: 'G-8EHS0KGEBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAku1d526eEuurq5kA4EcXb-B1pxx-BEYA',
    appId: '1:411331360468:android:c8724f1e649204565a2d41',
    messagingSenderId: '411331360468',
    projectId: 'gggg-2ee00',
    storageBucket: 'gggg-2ee00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_XBQWMf22Im2Teyl-VH8L6X93KXpRDIY',
    appId: '1:411331360468:ios:e3c58c5af29d01fc5a2d41',
    messagingSenderId: '411331360468',
    projectId: 'gggg-2ee00',
    storageBucket: 'gggg-2ee00.appspot.com',
    iosBundleId: 'com.example.appecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_XBQWMf22Im2Teyl-VH8L6X93KXpRDIY',
    appId: '1:411331360468:ios:03a24e17af1294e95a2d41',
    messagingSenderId: '411331360468',
    projectId: 'gggg-2ee00',
    storageBucket: 'gggg-2ee00.appspot.com',
    iosBundleId: 'com.example.appecom.RunnerTests',
  );
}
